### ISSUE TITLE
Event API returns 302 on store_event

### ISSUE THREAD

**Issue by ianbishop** [gosquared/ruby-client#4]
I had to actually go and pull down the gem to modify it so that I could see the actual error response. Please don't write code like:

``` ruby
return false unless response.status.to_s.starts_with?("20")
```

It makes it incredible difficult to figure out if something is wrong on my end.

---

The API returns an HTTP 302.

``` ruby
client = GoSquared::Event.new(:site_token => '..')
client.store_event('My Event', {:name => 'Ian'})
#<Faraday::Response... :status=>302>
=> false
```

**Comment by russellvaughan** [comment]
closing due to significant updates and inactivity.
