### ISSUE TITLE
Inject script doesn't check response is html

### ISSUE THREAD

**Issue by opsb** [gosquared/ruby-client#8]
Currently the filter doesn't check that the response type is html. A workaround is

```
  skip_after_filter :add_script, :unless => :html_response?
  def html_response?
    response.content_type == "text/html"
  end
```

but this check should be performed in this library

**Comment by russellvaughan** [comment]
Hey Oliver, thanks for opening this issue.

It's a good spot and I'll add the check to the library asap. 

Thanks again.

Russ

**Comment by russellvaughan** [comment]
Thanks again for bringing this to my attention Oliver, this check is now down in the library as per  commit bf8ca2eafc8508f3e45ff73a9966c7ab6ebd665e
